add pyproject.toml for build dependency on setuptools
resolve tox error:

> ERROR: Can not execute setup.py since setuptools is not available in the build environment.

Fixes: https://tracker.ceph.com/issues/67986

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 9f29e0bec86e927689d61a3e33e2d938692085ad)