ragweed: fix teuthology failure rel to pip issue 6264 cont..
Fixes: https://tracker.ceph.com/issues/49017

cont. fixing missing python module

```
ModuleNotFoundError: No module named
  'pip._vendor.cachecontrol'
```

Signed-off-by: Mark Kogan <mkogan@redhat.com>
(cherry picked from commit d16990990f1d4780473a15651ddf299d42eb5808)